/*
 * File: doctest_proxy.h
 * Project: quantt
 * File Created: Wednesday, 21st October 2020 9:25:55 am
 * Author: Alexandre Foley (Alexandre.foley@usherbrooke.ca)
 * -----
 * Last Modified: Wednesday, 21st October 2020 9:25:55 am
 * Modified By: Alexandre Foley (Alexandre.foley@usherbrooke.ca>)
 * -----
 * Copyright (c) 2020 Alexandre Foley
 * All rights reserved
 */
#ifndef DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES
#define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES
#endif // DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES

#ifndef QTT_PROXY_MACROS
#define QTT_PROXY_MACROS

#include "doctest.h"

#define DOXYSKIP_impl(x) /// @cond \	
x \
/// @endcond \

#define qtt_TEST_CASE DOCTEST_TEST_CASE
#define qtt_TEST_CASE_CLASS DOCTEST_TEST_CASE_CLASS
#define qtt_TEST_CASE_FIXTURE DOCTEST_TEST_CASE_FIXTURE
#define qtt_SUBCASE DOCTEST_SUBCASE
#define qtt_TEST_SUITE DOCTEST_TEST_SUITE
#define qtt_TEST_SUITE_BEGIN DOCTEST_TEST_SUITE_BEGIN
#define qtt_TEST_SUITE_END DOCTEST_TEST_SUITE_END
#define qtt_WARN DOCTEST_WARN
#define qtt_WARN_MESSAGE DOCTEST_WARN_MESSAGE
#define qtt_WARN_FALSE DOCTEST_WARN_FALSE
#define qtt_WARN_FALSE_MESSAGE DOCTEST_WARN_FALSE_MESSAGE
#define qtt_WARN_THROWS DOCTEST_WARN_THROWS
#define qtt_WARN_THROWS_MESSAGE DOCTEST_WARN_THROWS_MESSAGE
#define qtt_WARN_THROWS_AS DOCTEST_WARN_THROWS_AS
#define qtt_WARN_THROWS_AS_MESSAGE DOCTEST_WARN_THROWS_AS_MESSAGE
#define qtt_WARN_THROWS_WITH DOCTEST_WARN_THROWS_WITH
#define qtt_WARN_THROWS_WITH_MESSAGE DOCTEST_WARN_THROWS_WITH_MESSAGE
#define qtt_WARN_THROWS_WITH_AS DOCTEST_WARN_THROWS_WITH_AS
#define qtt_WARN_THROWS_WITH_AS_MESSAGE DOCTEST_WARN_THROWS_WITH_AS_MESSAGE
#define qtt_WARN_NOTHROW DOCTEST_WARN_NOTHROW
#define qtt_WARN_NOTHROW_MESSAGE DOCTEST_WARN_NOTHROW_MESSAGE
#define qtt_CHECK DOCTEST_CHECK
#define qtt_CHECK_MESSAGE DOCTEST_CHECK_MESSAGE
#define qtt_CHECK_FALSE DOCTEST_CHECK_FALSE
#define qtt_CHECK_FALSE_MESSAGE DOCTEST_CHECK_FALSE_MESSAGE
#define qtt_CHECK_THROWS DOCTEST_CHECK_THROWS
#define qtt_CHECK_THROWS_MESSAGE DOCTEST_CHECK_THROWS_MESSAGE
#define qtt_CHECK_THROWS_AS DOCTEST_CHECK_THROWS_AS
#define qtt_CHECK_THROWS_AS_MESSAGE DOCTEST_CHECK_THROWS_AS_MESSAGE
#define qtt_CHECK_THROWS_WITH DOCTEST_CHECK_THROWS_WITH
#define qtt_CHECK_THROWS_WITH_MESSAGE DOCTEST_CHECK_THROWS_WITH_MESSAGE
#define qtt_CHECK_THROWS_WITH_AS DOCTEST_CHECK_THROWS_WITH_AS
#define qtt_CHECK_THROWS_WITH_AS_MESSAGE DOCTEST_CHECK_THROWS_WITH_AS_MESSAGE
#define qtt_CHECK_NOTHROW DOCTEST_CHECK_NOTHROW
#define qtt_CHECK_NOTHROW_MESSAGE DOCTEST_CHECK_NOTHROW_MESSAGE
#define qtt_REQUIRE DOCTEST_REQUIRE
#define qtt_REQUIRE_MESSAGE DOCTEST_REQUIRE_MESSAGE
#define qtt_REQUIRE_FALSE DOCTEST_REQUIRE_FALSE
#define qtt_REQUIRE_FALSE_MESSAGE DOCTEST_REQUIRE_FALSE_MESSAGE
#define qtt_REQUIRE_THROWS DOCTEST_REQUIRE_THROWS
#define qtt_REQUIRE_THROWS_MESSAGE DOCTEST_REQUIRE_THROWS_MESSAGE
#define qtt_REQUIRE_THROWS_AS DOCTEST_REQUIRE_THROWS_AS
#define qtt_REQUIRE_THROWS_AS_MESSAGE DOCTEST_REQUIRE_THROWS_AS_MESSAGE
#define qtt_REQUIRE_THROWS_WITH_AS DOCTEST_REQUIRE_THROWS_WITH_AS
#define qtt_REQUIRE_THROWS_WITH_AS_MESSAGE DOCTEST_REQUIRE_THROWS_WITH_AS_MESSAGE
#define qtt_REQUIRE_NOTHROW DOCTEST_REQUIRE_NOTHROW
#define qtt_REQUIRE_NOTHROW_MESSAGE DOCTEST_REQUIRE_NOTHROW_MESSAGE

#define qtt_SCENARIO DOCTEST_SCENARIO
#define qtt_GIVEN DOCTEST_GIVEN
#define qtt_WHEN DOCTEST_WHEN
#define qtt_AND_WHEN DOCTEST_AND_WHEN
#define qtt_THEN DOCTEST_THEN
#define qtt_AND_THEN DOCTEST_AND_THEN

#define qtt_WARN_EQ DOCTEST_WARN_EQ
#define qtt_CHECK_EQ DOCTEST_CHECK_EQ
#define qtt_REQUIRE_EQ DOCTEST_REQUIRE_EQ
#define qtt_WARN_NE DOCTEST_WARN_NE
#define qtt_CHECK_NE DOCTEST_CHECK_NE
#define qtt_REQUIRE_NE DOCTEST_REQUIRE_NE
#define qtt_WARN_GT DOCTEST_WARN_GT
#define qtt_CHECK_GT DOCTEST_CHECK_GT
#define qtt_REQUIRE_GT DOCTEST_REQUIRE_GT
#define qtt_WARN_LT DOCTEST_WARN_LT
#define qtt_CHECK_LT DOCTEST_CHECK_LT
#define qtt_REQUIRE_LT DOCTEST_REQUIRE_LT
#define qtt_WARN_GE DOCTEST_WARN_GE
#define qtt_CHECK_GE DOCTEST_CHECK_GE
#define qtt_REQUIRE_GE DOCTEST_REQUIRE_GE
#define qtt_WARN_LE DOCTEST_WARN_LE
#define qtt_CHECK_LE DOCTEST_CHECK_LE
#define qtt_REQUIRE_LE DOCTEST_REQUIRE_LE
#define qtt_WARN_UNARY DOCTEST_WARN_UNARY
#define qtt_CHECK_UNARY DOCTEST_CHECK_UNARY
#define qtt_REQUIRE_UNARY DOCTEST_REQUIRE_UNARY
#define qtt_WARN_UNARY_FALSE DOCTEST_WARN_UNARY_FALSE
#define qtt_CHECK_UNARY_FALSE DOCTEST_CHECK_UNARY_FALSE
#define qtt_REQUIRE_UNARY_FALSE DOCTEST_REQUIRE_UNARY_FALSE

#endif // MY_PROXY_MACROS